apiVersion: v1
kind: Secret
metadata:
  name: spark-user-secret
  namespace: <tenant name>
type: Opaque
data:
  MAPR_SPARK_USER:          <Base64 encoded value of username>
  MAPR_SPARK_PASSWORD:      <Base64 encoded value of password>
  MAPR_SPARK_GROUP:         <Base64 encoded value of group>
  MAPR_SPARK_UID:           <Base64 encoded value of uid>
  MAPR_SPARK_GID:           <Base64 encoded value of gid>
  SECURE_CLUSTER:           <Base64 encoded value of true or false>
