apiVersion: v1
kind: Secret
metadata:
  name: spark-user-secret
  namespace: sampletenant
type: Opaque
data:
  MAPR_SPARK_USER:     bWFwcg==
  MAPR_SPARK_PASSWORD: bWFwcg==
  MAPR_SPARK_GROUP:    bWFwcg==
  MAPR_SPARK_UID:      NTAwMA==
  MAPR_SPARK_GID:      NTAwMA==
  SECURE_CLUSTER:      ZmFsc2U=
