#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#########################################################################################################
# This is an example of spark app configuration that is able to work with kerberised solr and zookeeper #
# All config files and keytab are mounted here using configMaps and secrets, but this is not the only   #
# way to add these files to container.                                                                  #
#########################################################################################################
#
# To run this configuration, the following files are required:
# - jaas config
# - kerberos config
# - user keytab
#
# All these files should be present in both driver and executor pods.
# For example, create configmaps for conf files and put keytab into a secret:
# kubectl create cm solr-jaas-client-conf -n [tenant-ns] --from-file /path/to/jaas.conf
# kubectl create cm kerberos-conf -n [tenant-ns] --from-file /path/to/krb5.conf
# kubectl create secret generic solr-keytab -n [tenant-ns] --from-file /path/to/user.keytab
#
# Then mount values from these maps and secret as shown in this example below.
#
# To configure spark to use there files, make sure to:
# - specify path to krb5.conf file via "java.security.krb5.conf" property
# - specify name of jaas configuration via "solr.kerberos.jaas.appname" property
# - specify path to jaas.conf file via env variable "SOLR_JAAS_CONF"
# These changes should be applied to both driver and executor specs.
#
# Spark image contains a prebuilt spark-solr connector that must be used. It's included to classpath via deps.jars.
#
# Important: avoid using default name of jaas config like 'Client'. It will lead to spark app failure.
# Use recognizable name like "SolrApp"
#


apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: solr-demo
  namespace: sampletenant
spec:
  sparkConf:
  #    spark.mapr.user.secret: mapr-secret
  #    spark.eventLog.enabled: "false"
  #    spark.eventLog.dir: "maprfs:///apps/spark/sampletenant"

  type: Scala
  sparkVersion: 2.4.7
  mode: cluster
  image: gcr.io/mapr-252711/spark-2.4.7:202209072129P152
  imagePullPolicy: Always
  mainApplicationFile: maprfs:///path/to/application.jar
  mainClass: your.main.Class
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  deps:
    jars:
      - "local:///opt/mapr/spark/spark-2.4.7/external_jars/spark-solr-3.9.0_2.12.jar"
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.7
#      serviceAccount: hpe-sampletenant
    # Driver SOLR+KERBEROS-specific options
    javaOptions: "-Dsolr.kerberos.jaas.appname=[config-name-from-jaas.conf] -Djava.security.krb5.conf=[path-to-mounted-kerberos-config]"
    env:
      - name: SOLR_JAAS_CONF
        value: "[path-to-mounted-jaas-config]"
    secrets:
      - name: solr-keytab
        path: /keytabs
        secretType: Generic
    configMaps:
      - name: solr-jaas-client-conf
        path: /mnt/solr
      - name: kerberos-conf
        path: /mnt/kerberos
  executor:
    instances: 2
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.7
    # Executor SOLR+KERBEROS-specific options
    env:
      - name: SOLR_JAAS_CONF
        value: "[path-to-mounted-jaas-config]"
    javaOptions: "-Dsolr.kerberos.jaas.appname=[config-name-from-jaas.conf] -Djava.security.krb5.conf=[path-to-mounted-kerberos-config]"
    secrets:
      - name: solr-keytab
        path: /keytabs
        secretType: Generic
    configMaps:
      - name: solr-jaas-client-conf
        path: /mnt/solr
      - name: kerberos-conf
        path: /mnt/kerberos
