apiVersion: hcp.hpe.com/v1
kind: Tenant
metadata:
  name: sampletenant
spec:
  clustername: dataplatform
  clustertype: internal
  baseimagetag: "202104010902C"
  imageregistry: gcr.io/mapr-252711
  imagepullsecret: imagepull
  loglocation: /var/log/mapr
  corelocation: /var/log/mapr/cores
  podinfolocation: /var/log/mapr/podinfo
  debugging:
    loglevel: INFO
    preservefailedpods: true
    wipelogs: false
  tenantservices:
    tenantcli:
      count: 1
    hivemetastore:
      count: 1
    sparkhs:
      count: 1
    sparkstandalone:
      count: 3
      mastercount: 1
      uiproxycount: 1
    sparkts:
      count: 1
    livy:
      count: 1
  tenantcustomizationfiles:
    hivemetastoreconfig: hivemeta-cm
    sparkhsconfig: sparkhs-cm
    sparktsconfig: sparkthrift-cm
    sparkmasterconfig: sparkmaster-cm
    sparkworkerconfig: sparkworker-cm
    sparkuiproxyconfig: sparkuiproxy-cm
    livyconfig: livy-cm
  userlist:
    - user1
    - user2
  grouplist:
    - group1
    - group2
