apiVersion: v1
kind: ConfigMap
metadata:
  name: mapr-external-cm
  namespace: hpe-externalclusterinfo
date:
  MAPR_HOME: >-
    /opt/mapr
  clusterid: >-
    <clusterid>
  MAPR_CLUSTER: >-
    gce1.cluster.com
  clustername: >-
    gce1.cluster.com
  SECURE_CLUSTER: >-
    true
  disableSecurity: >-
    false
  cldbLocations: <host>[:<port>][,<host>:[<port>]...]
  MAPR_CLDB_HOSTS: <host>[:<port>][,<host>:[<port>]...]
  zkLocations: <host>[:<port>][,<host>:[<port>]...]
  MAPR_ZK_HOSTS: <host>[:<port>][,<host>:[<port>]...]
  esLocations: <host>[:<port>][,<host>:[<port>]...]
  tsdbLocations: <host>[:<port>][,<host>:[<port>]...]
  hivemetaLocations: <host>[:<port>][,<host>:[<port>]...]
  mastgatewayLocations: <host>[:<port>][,<host>:[<port>]...]
  maprgatewayLocations: <host>[:<port>][,<host>:[<port>]...]
  dagLocations: <host>[:<port>][,<host>:[<port>]...]
  nfsLocations: <host>[:<port>][,<host>:[<port>]...]
  nfs4Locations: <host>[:<port>][,<host>:[<port>]...]
  objectstoreLocations: <host>[:<port>][,<host>:[<port>]...]
  kafkarestLocations: <host>[:<port>][,<host>:[<port>]...]
  mfsLocations: <host>[:<port>][,<host>:[<port>]...]
  hoststatsLocations: <host>[:<port>][,<host>:[<port>]...]
  apiserverLocations: <host>[:<port>][,<host>:[<port>]...]
  nodemanagerLocations: <host>[:<port>][,<host>:[<port>]...]
  resourcemanagerLocations: <host>[:<port>][,<host>:[<port>]...]
  hbaseLocations: <host>[:<port>][,<host>:[<port>]...]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mapr-hivesite-cm
  namespace: hpe-externalclusterinfo
  annotations:
    mapr.com/externalcluster: "gce1.cluster.com"
data:
  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="configuration.xsl"?><!-- Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. --><configuration> <property> <name>hive.metastore.uris</name> <value>thrift://scott-mapr-core-w2t3.c.mapr-252711.internal:9083</value> </property> <property> <name>javax.jdo.option.ConnectionURL</name> <value>jdbc:derby:;databaseName=/opt/mapr/hive/hive-2.3/metastore_db;create=true</value> <description>JDBC connect string for a JDBC metastore</description> </property> <property> <name>hive.metastore.sasl.enabled</name> <value>true</value> </property> <property> <name>hive.server2.thrift.sasl.qop</name> <value>auth-conf</value> </property> <property> <name>hive.metastore.execute.setugi</name> <value>false</value> </property> <property> <name>hive.security.metastore.authorization.manager</name> <value>org.apache.hadoop.hive.ql.security.authorization.StorageBasedAuthorizationProvider</value> </property> <property> <name>hive.server2.webui.use.pam</name> <value>true</value> </property> <property> <name>hive.server2.webui.use.ssl</name> <value>true</value> </property> <property> <name>hive.server2.use.SSL</name> <value>true</value> </property> <property> <name>hive.users.in.admin.role</name> <value>mapr</value> </property> <property> <name>hive.conf.restricted.list</name> <value>hive.security.authenticator.manager,hive.security.authorization.manager,hive.security.metastore.authorization.manager,hive.security.metastore.authenticator.manager,hive.users.in.admin.role,hive.server2.xsrf.filter.enabled,hive.security.authorization.enabled,hive.server2.authentication.ldap.baseDN,hive.server2.authentication.ldap.url,hive.server2.authentication.ldap.Domain,hive.server2.authentication.ldap.groupDNPattern,hive.server2.authentication.ldap.groupFilter,hive.server2.authentication.ldap.userDNPattern,hive.server2.authentication.ldap.userFilter,hive.server2.authentication.ldap.groupMembershipKey,hive.server2.authentication.ldap.userMembershipKey,hive.server2.authentication.ldap.groupClassKey,hive.server2.authentication.ldap.customLDAPQuery,hive.exec.pre.hooks,hive.exec.post.hooks,hive.exec.failure.hooks,hive.exec.query.redactor.hooks,hive.semantic.analyzer.hook,hive.query.lifetime.hooks,hive.exec.driver.run.hooks,hive.server2.session.hook</value> </property> <property> <name>hive.security.authorization.enabled</name> <value>true</value> </property> <property> <name>hive.security.authorization.manager</name> <value>org.apache.hadoop.hive.ql.security.authorization.plugin.fallback.FallbackHiveAuthorizerFactory</value> </property> <property> <name>hive.server2.metrics.enabled</name> <value>true</value> </property> <property> <name>hive.server2.metrics.file.location</name> <value>/tmp/hiveserver2_report.json</value> </property> <property> <name>hive.metastore.metrics.enabled</name> <value>true</value> </property> <property> <name>hive.metastore.metrics.file.location</name> <value>/tmp/hivemetastore_report.json</value> </property> <property> <name>hive.service.metrics.reporter</name> <value>JSON_FILE,JMX</value> </property> </configuration>
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-user-secrets
  namespace: hpe-externalclusterinfo
  annotations:
    mapr.com/clutername: "<clustername>"
type: Opaque
data:
  MAPR_USER:     <Base64 encoded value of username>
  MAPR_PASSWORD: <Base64 encoded value of password>
  MAPR_GROUP:    <Base64 encoded value of group>
  MAPR_UID:      <Base64 encoded value of uid>
  MAPR_GID:      <Base64 encoded value of gid>
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-server-secrets
  namespace: hpe-externalclusterinfo
  annotations:
    mapr.com/clutername: "<clustername>"
type: Opaque
data:
  clusterid: <Base64 Encoded value of clusterid from External MapR cluster>
  maprmetricsticket: <Base64 Encoded value of maprserverticket from External MapR cluster>
  maprserverticket: <Base64 Encoded value of maprserverticket from External MapR cluster>
  ssl_keystore: <Base64 Encoded value of ssl_keystore from External MapR cluster>
  ssl_keystore.p12: <Base64 Encoded value for P12 keystore file>
  ssl_keystore.pem: <Base64 Encoded value for keystore PEM file>
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-client-secrets
  namespace: hpe-externalclusterinfo
  annotations:
    mapr.com/clutername: "<clustername>"
type: Opaque
data:
  ssl_truststore: <Base64 Encoded value of ssl_truststore from External MapR cluster>
  ssl_truststore.p12: <Base64 Encoded value of P12 truststore file>
  ssl_truststore.pem: <Base64 Encoded value for truststore PEM file>
