apiVersion: hcp.hpe.com/v1
kind: Tenant
metadata:
  name: sampletenant
spec:
  clustername: dataplatform
  clustertype: internal
  baseimagetag: "202202281231P150"
  imageregistry: gcr.io/mapr-252711
