apiVersion: hcp.hpe.com/v1
kind: DataPlatform
metadata:
  name: dataplatform
spec:
  baseimagetag: "202209072129P152"
  imageregistry: gcr.io/mapr-252711
  imagepullsecret: hpe-imagepull-secrets
  environmenttype: hcp
  disableha: false
  scheduleonmaster: true
  dnsdomain: cluster.local
  loglocation: /var/log/mapr
  corelocation: /var/mapr/cores
  podinfolocation: /var/mapr/podinfo
  security:
    disablesecurity: false
    systemusersecret: system-user-secrets
    usedare: false
    selinuxinfo:
      overwriteselinux: false
      level: "s0:c123,c456"
  debuginfo:
    loglevel: INFO
    preservefailedpods: false
    wipelogs: false
    version: 6.2.0
  core:
    init:
      image: init-6.2.0:202209072129P152
      requestcpu: "1000m"
      limitcpu: "16000m"
      requestmemory: 1Gi
      limitmemory: 4Gi
      requestdisk: 10Gi
      limitdisk: 20Gi
      loglevel: INFO
    zookeeper:
      failurecount: 1
      image: zookeeper-6.2.0:202209072129P152
      requestcpu: "1000m"
      limitcpu: "3000m"
      requestmemory: 1Gi
      limitmemory: 1Gi
      requestdisk: 20Gi
      limitdisk: 30Gi
      loglevel: INFO
    cldb:
      failurecount: 1
      image: cldb-6.2.0:202209072129P152
      requestcpu: "8000m"
      limitcpu: "20000m"
      requestmemory: 16Gi
      limitmemory: 26Gi
      requestdisk: 30Gi
      limitdisk: 60Gi
      sshport: 5000
      loglevel: INFO
      hostports:
        - hostport: 7220
        - hostport: 7443
        - hostport: 7222
        - hostport: 5660
        - hostport: 5692
        - hostport: 5724
        - hostport: 5756
        - hostport: 8660
    admincli:
      count: 1
      image: admincli-6.2.0:202209072129P152
      sshport: 5003
      requestcpu: "500m"
      limitcpu: "2000m"
      requestmemory: 1Gi
      limitmemory: 1Gi
      requestdisk: 20Gi
      limitdisk: 30Gi
      loglevel: INFO
    webserver:
      count: 1
      image: webserver-6.2.0:202209072129P152
      sshport: 5002
      requestcpu: "1000m"
      limitcpu: "2000m"
      requestmemory: 2Gi
      limitmemory: 2Gi
      requestdisk: 20Gi
      limitdisk: 30Gi
      loglevel: INFO
  gateways:
    nfs: false
    mast: false
    objectstore:
      image: objectstore-2.2.0:202209072129P152
      zones:
        - name: zone1
          count: 1
          sshport: 5010
          size: 5Gi
          fspath: ""
          hostports:
            - hostport: 9000
              nodeport: 31900
          requestcpu: "1000m"
          limitcpu: "4000m"
          requestmemory: 2Gi
          limitmemory: 2Gi
          requestdisk: 20Gi
          limitdisk: 30Gi
          loglevel: INFO
